// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240131075345_createeee")]
    partial class createeee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.ListModels.FamilyArticleList", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArticleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ArticleQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.HasKey("ArticleId");

                    b.ToTable("FamilyArticleList");
                });

            modelBuilder.Entity("Domain.Models.ListModels.SommarHusArticleList", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArticleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ArticleQuantity")
                        .HasColumnType("int");

                    b.Property<string>("HouseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid>("SommarHusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArticleId");

                    b.ToTable("SommarHusLists");
                });

            modelBuilder.Entity("Domain.Models.UserModel.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("08260479-52a0-4c0e-a588-274101a2c3be"),
                            Password = "$2a$11$f2hCeEnyg1iOsIL1j6/mQ.Iv1wiMO9Rbf2W/CvCDTvK4L9ECbshs.",
                            Username = "Bojan"
                        },
                        new
                        {
                            UserId = new Guid("047425eb-15a5-4310-9d25-e281ab036868"),
                            Password = "$2a$11$u8vPjCaoiL6ljfnLI3vhAOLrStsZXC6BJ/V9MXCFO9x3cbspCCKgq",
                            Username = "Sandra"
                        },
                        new
                        {
                            UserId = new Guid("047425eb-15a5-4310-9d25-e281ab036869"),
                            Password = "$2a$11$akwWEK20OoZimDJhCRDgUeb6tLgUS/RZ5tN.xVEEmh8E2kC74iUrm",
                            Username = "Mohamed"
                        },
                        new
                        {
                            UserId = new Guid("047425eb-15a5-4310-9d25-e281ab036870"),
                            Password = "$2a$11$mcTHDqzWGO1xThBx3sv0gOPzBd54GmR8ak79ZyzLJvY5/ppydfgOO",
                            Username = "Felix"
                        },
                        new
                        {
                            UserId = new Guid("047425eb-15a5-4310-9d25-e281ab036871"),
                            Password = "$2a$11$Eo3NgMUIAwSlVVSBVH7gw.xJWnV09SITzdbdti6o0SPYfVFIwCFgW",
                            Username = "Kamphol"
                        },
                        new
                        {
                            UserId = new Guid("047425eb-15a5-4310-9d25-e281ab036872"),
                            Password = "$2a$11$MjStOR2g24BbVfF0MddnJeV5N0f1lZDy/AqBd7Wo0xbXj.Mzu1n/2",
                            Username = "Louis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
